### ISSUE TITLE
Microexpressions Unmasking 

### ISSUE THREAD

**Issue by dilipkrbe** [microsoft/AI-Chat-App-Hack#134]
### Project name

Microexpressions unmasking

### Description

Face the Truth: Unmasking Microexpressions with Computer Vision and Meta’s SegmentAnything

### Language

English

### Project Repository URL

https://github.com/dilipkrbe/microexpressions-unmasking

### Project video

Tbd

### Team members

Dilipkrbhat@gmail.com

### Showcase Consent

Yes

**Comment by dilipkrbe** [comment]
Face the Truth: Unmasking Microexpressions with Computer Vision and Meta’s SegmentAnything

**Comment by pamelafox** [comment]
Ah I now see the repository is empty. Given the submission deadline was yesterday and we've begun judging, I don't think we can consider this one. Sorry!
