### ISSUE TITLE
Uneccessary reprocessing with datalake storage gen2

### ISSUE THREAD

**Issue by fragpk** [microsoft/AI-Chat-App-Hack#147]
With datalake storage, every time i run azd up, it processes docs from the beggining. This wasn't happening with local files. How can we avoid the uneccessary reprocessing?

**Comment by pamelafox** [comment]
Could you file this issue in https://github.com/Azure-Samples/azure-search-openai-demo/ if you haven't already? I think we have some improvements to make with ADLS2 ingestion.
