### ISSUE TITLE
Add to Calendar link is not available for users outside of Microsoft

### ISSUE THREAD

**Issue by kevball2** [microsoft/AI-Chat-App-Hack#26]
The calendar link is only available for users internal to Microsoft (https://microsoft-my.sharepoint.com/personal/joshoh_microsoft_com/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fjoshoh%5Fmicrosoft%5Fcom%2FDocuments%2FHack%20Together%20AI%20Chat%20App%2FChat%20App%20Calendar%2Eics)

Could the calendar file be added to the GitHub Repo or to another public facing URL?

**Comment by multispark** [comment]
Fixed!
